// Generated by gencpp from file car_move/AddTwoInts.msg
// DO NOT EDIT!


#ifndef CAR_MOVE_MESSAGE_ADDTWOINTS_H
#define CAR_MOVE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <car_move/AddTwoIntsRequest.h>
#include <car_move/AddTwoIntsResponse.h>


namespace car_move
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace car_move


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car_move::AddTwoInts > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::car_move::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::car_move::AddTwoInts > {
  static const char* value()
  {
    return "car_move/AddTwoInts";
  }

  static const char* value(const ::car_move::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::car_move::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::car_move::AddTwoInts >
template<>
struct MD5Sum< ::car_move::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car_move::AddTwoInts >::value();
  }
  static const char* value(const ::car_move::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_move::AddTwoIntsRequest> should match
// service_traits::DataType< ::car_move::AddTwoInts >
template<>
struct DataType< ::car_move::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::car_move::AddTwoInts >::value();
  }
  static const char* value(const ::car_move::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car_move::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::car_move::AddTwoInts >
template<>
struct MD5Sum< ::car_move::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car_move::AddTwoInts >::value();
  }
  static const char* value(const ::car_move::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_move::AddTwoIntsResponse> should match
// service_traits::DataType< ::car_move::AddTwoInts >
template<>
struct DataType< ::car_move::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::car_move::AddTwoInts >::value();
  }
  static const char* value(const ::car_move::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_MOVE_MESSAGE_ADDTWOINTS_H
